apiVersion: v1
data:
  prometheus-datasource.json: |
    {
      "name": "Prometheus",
      "type": "prometheus",
      "url": "http://prometheus:9090",
      "access": "proxy",
      "basicAuth": false
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-import-datasource
  namespace: monitoring

---
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-import-datasource
  namespace: monitoring
  labels:
    app: grafana
    component: import-datasource
spec:
  template:
    metadata:
      name: grafana-import-datasource
      labels:
        app: grafana
        component: import-datasource
    spec:
      serviceAccountName: prometheus-k8s
      initContainers:
      - name: wait-for-grafana
        image: giantswarm/tiny-tools
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          while [ $(curl -Lsw '%{http_code}' "http://grafana:3000" -o /dev/null) -ne 200 ]; do
            echo '.'
            sleep 15;
          done
      containers:
      - name: grafana-import-datasource
        image: giantswarm/tiny-tools
        command: ["/bin/sh", "-c"]
        workingDir: /opt/grafana-import-datasource
        args:
          - >
            for file in *-datasource.json ; do
              if [ -e "$file" ] ; then
                echo "importing $file" &&
                curl --silent --fail --show-error \
                  --request POST http://${GF_ADMIN_USER}:${GF_ADMIN_PASSWORD}@grafana:3000/api/datasources \
                  --header "Content-Type: application/json" \
                  --data-binary "@$file" ;
                echo "" ;
              fi
            done
        env:
        - name: GF_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-username
        - name: GF_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-password
        volumeMounts:
        - name: config-volume
          mountPath: /opt/grafana-import-datasource
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: grafana-import-datasource
