# apiVersion: monitoring.coreos.com/v1
# kind: Prometheus
# metadata:
#   name: prometheus
# spec:
#   replicas: 2
#   resources:
#     requests:
#       memory: 400Mi
#   additionalScrapeConfigs:
#     name: additional-scrape-configs
#     key: prometheus-additional.yaml
