---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  namespaceSelector:
    matchNames:
    - ingress
  endpoints:
  - interval: 5s
    path: /metrics
    port: prometheus
